server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      route-refresh-listener:
        enabled: true
      routes:
        - id: user-server
          uri: http://localhost:8090
          predicates:
            - name: Path
              args:
                patterns: /user/**